### ISSUE TITLE
Invalid QEMU-savevm magic

### ISSUE THREAD

**Issue by mbushou** [juergh/lqs2mem#2]
Hi, thanks for this tool!  I've used it successfully in the past on QEMU v2.0.0 and KVM, but I recently came across this problem on QEMU 2.4.1 and Xen.  Any ideas?  Conducted in a Fedora 23 dom0 running on Xen 4.5.2.

```
$ sudo virsh dump my_vm test.virsh.dump

Domain my_vm dumped to test.virsh.dump

$ sudo chown micah:micah test.virsh.dump

$ ./lqs2mem/lqs2mem -w pc.ram test.virsh.dump test.raw.dump
Invalid QEMU-savevm magic
Unrecogized file format

$ dnf list installed |grep qemu
libvirt-daemon-driver-qemu.x86_64     1.2.18.2-2.fc23           @updates        
qemu-common.x86_64                    2:2.4.1-6.fc23            @updates        
qemu-guest-agent.x86_64               2:2.4.1-6.fc23            @updates        
qemu-img.x86_64                       2:2.4.1-6.fc23            @updates        
qemu-kvm.x86_64                       2:2.4.1-6.fc23            @updates        
qemu-system-x86.x86_64                2:2.4.1-6.fc23            @updates  
```

**Comment by juergh** [comment]
Hmm... I tried this on F23 with KVM but I'm getting a different error:

`
$ ./lqs2mem -d 7 -l f23.dump 
Checking for Libvirt-QEMU-save magic...
Invalid Libvirt-QEMU-save magic
Checking for QEMU-savevm magic...
Found QEMU-savevm magic
QEMU-savevm version = 3

Section 0
offset          : 0x0000000000000008
Segmentation fault
`

Can you run your test like so:
`
$ ./lqs2mem/lqs2mem -d 7 -l test.virsh.dump
`

**Comment by mbushou** [comment]
Thanks for the quick reply!

I am using Xen as the hypervisor with libvirt.  It appears that libvirt produces a core file instead of a QEMU suspend to disk file.  Do you think this is related to Xen or to the QEMU version I'm using?  

Thanks!

```
$ sudo virsh dump my_vm test.virsh.dump

Domain my_vm dumped to test.virsh.dump

$ file test.virsh.dump
test.virsh.dump: ELF 64-bit LSB core file x86-64, version 1

$ ./lqs2mem/lqs2mem -d 7 -l test.virsh.dump
Checking for Libvirt-QEMU-save magic...
Invalid Libvirt-QEMU-save magic
Checking for QEMU-savevm magic...
Invalid QEMU-savevm magic
Unrecogized file format
```

**Comment by juergh** [comment]
If you're using XEN then there is no QEMU in the picture. So you won't get a QEMU suspend-to-disk file. I'm not familiar with XEN so don't know what you get when you dump a XEN guest through virsh.

**Comment by mbushou** [comment]
Ok, thanks!  This can be confusing, but I believe when running a guest using full virtualization, Xen does use /usr/lib/xen/bin/qemu-system-i386.  At least this is what appears when running top on dom0!  I'll keep working at it, thanks for your help.
